
services:
  
  pgvector:
    image: ankane/pgvector:latest
    hostname: pgvector
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    volumes:
      - ./infra/pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - app_network

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - app_network
       
volumes:
  pgvector_data:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge