
services:
  
  pgvector:
    image: ankane/pgvector:latest
    hostname: pgvector
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    volumes:
      - ./infra/pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network


  fastapi-app:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      WEAVIATE_URL: "http://weaviate:8080"
      SUPERTOKENS_URL: "http://supertokens:3567"
    depends_on:
      - pgvector
      - redis
    networks:
      - app_network
  

  nginx:
    profiles:
      - production
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/gdai.conf:/etc/nginx/conf.d/gdai.conf
      - ../ssl/fullchain.pem:/etc/letsencrypt/fullchain.pem
      - ../ssl/privkey.pem:/etc/letsencrypt/privkey.pem
    depends_on:
      - fastapi-app
    networks:
      - app_network
    
volumes:
  pgvector_data:
  redis_data:

networks:
  app_network:
    driver: bridge