name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEPLOY }}
          username: ${{ secrets.SSH_USER_DEPLOY }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}
          port: ${{ secrets.SSH_PORT_DEPLOY }} 
          script: |
            cd /home/gdai/
            git pull origin main
            docker-compose up -d --force-recreate