name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:

  deploy_documentation:
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-dracula-theme
      - run: mkdocs build
      - run: mkdocs gh-deploy --force
