name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEPLOY }}
          username: ${{ secrets.SSH_USER_DEPLOY }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}
          port: ${{ secrets.SSH_PORT_DEPLOY }}
          script: |
            cd /home/gdai/gdai/
            git pull origin main
            docker-compose --profile production down
            docker-compose --profile production up -d
  deploy_documentation:
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: mkdocs gh-deploy --force
